services:
  - type: web
    name: alist-proxy
    env: go
    plan: free
    buildCommand: go mod tidy && go build -o bin/alist-proxy -ldflags="-w -s" .
    startCommand: ./bin/alist-proxy
    healthCheckPath: /health
    envVars:
      - key: PORT
        sync: false
      - key: ALIST_ADDRESS
        sync: false
      - key: ALIST_TOKEN
        sync: false
    autoDeploy: true
    branch: main
